### ISSUE TITLE
Suggestions for Development 

### ISSUE THREAD

**Issue by cujo11807** [polodarb/Flashlight-Tiramisu#3]
Hello,
I think what you've created here is a great representation of what Android 13 is capable of, and with future updates I'm going to guess a press+hold on the quicksettings shortcut for the flashlight will open a flashlight slider, or a slider will be implemented into the shortcut. Either way, here's what I'd like to see in the meantime with your app:

A way to set the value to '1%(or lowest value),' '25%', and '100%' (dimmest setting, nighttime, daytime, etc.) I found that with my Pixel 6, the minimum brightness was best for lighting up a small room at night without blinding anything and anyone around you, around 25% is sort of a middle-ground with any further increases causing exponentially less real-world improvements in light, though there is and will be a noticable increase in light when jumping between 25% and 100%. 

Along with that, a simple on/off switch would be nice along with the app having a memory of what the last brightness value was when the app was last open.

Keep developing, we need it,
-Curtis

**Comment by cyb3rko** [comment]
A had similiar ideas and I wanted a more advanced interface, so I experimented a bit and wrote my own app.
So maybe this could be interesting to you: https://github.com/cyb3rko/flashdim

Until it's published on Google Play and F-Droid you can download an apk file in the releases tab and test it out :)

**Comment by polodarb** [comment]
> Hello, I think what you've created here is a great representation of what Android 13 is capable of, and with future updates I'm going to guess a press+hold on the quicksettings shortcut for the flashlight will open a flashlight slider, or a slider will be implemented into the shortcut. Either way, here's what I'd like to see in the meantime with your app:
> 
> A way to set the value to '1%(or lowest value),' '25%', and '100%' (dimmest setting, nighttime, daytime, etc.) I found that with my Pixel 6, the minimum brightness was best for lighting up a small room at night without blinding anything and anyone around you, around 25% is sort of a middle-ground with any further increases causing exponentially less real-world improvements in light, though there is and will be a noticable increase in light when jumping between 25% and 100%.
> 
> Along with that, a simple on/off switch would be nice along with the app having a memory of what the last brightness value was when the app was last open.
> 
> Keep developing, we need it, -Curtis

Hello! Thanks for the wishes and advice, I'm already developing an update. I'll try to do whatever you want :)

**Comment by polodarb** [comment]
Hey, @cyb3rko , thanks for the mention, I wish you development and success :D

**Comment by cyb3rko** [comment]
Thanks, can only give back those wishes.
And especially for your country as well ❤️‍🩹

**Comment by polodarb** [comment]
@TarasH1 Hello, yes, I will release an update soon. I have very little left
